const drivers = [
    "https://i.imgur.com/90DoKYV.png",
    "https://i.imgur.com/FoIPyf9.png",
    "https://i.imgur.com/YFiOYfa.png",
    "https://i.imgur.com/tHavptT.png",
    "https://i.imgur.com/vtJffuU.png",
    "https://i.imgur.com/g37tfJo.png",
    "https://i.imgur.com/CDbSwwp.png",
    "https://i.imgur.com/hohdoHG.png",
    "https://i.imgur.com/AbvcT8t.png",
    "https://i.imgur.com/mWK5arP.png",
    "https://i.imgur.com/ginauBw.png",
    "https://i.imgur.com/l1ZSbnL.png",
    "https://i.imgur.com/WSeTc9X.png",
    "https://i.imgur.com/SbH53fY.png",
    "https://i.imgur.com/WPEXAg5.png",
    "https://i.imgur.com/39lOqc5.png",
    "https://i.imgur.com/eFeC96d.png",
    "https://i.imgur.com/bmuZmF9.png",
    "https://i.imgur.com/J67axnw.png",
    "https://i.imgur.com/n7jnKXy.png",
];

const teams = [
    "https://i.imgur.com/gIInfgL.png",
    "https://i.imgur.com/wB3S200.png",
    "https://i.imgur.com/aEtqKWm.png",
    "https://i.imgur.com/MGgtRa4.png",
    "https://i.imgur.com/iDq2MeG.png",
    "https://i.imgur.com/c3eOciU.png",
    "https://i.imgur.com/xsUCWCh.png",
    "https://i.imgur.com/CqlRW6S.png",
    "https://i.imgur.com/yzQOYyu.png",
    "https://i.imgur.com/DX6MJWY.png",
];